//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Fact
    {
        public int ID { get; set; }
        public string CMD { get; set; }
        public string FACT { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Facture Facture { get; set; }
    }
}
