//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reglement
    {
        public string ID { get; set; }
        public string FACT { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Montant { get; set; }
        public string Type_Reg { get; set; }
    
        public virtual Facture Facture { get; set; }
    }
}
